use tienda;
select nombre from producto;
select nombre, precio from producto;
select * from producto;
select nombre, precio as precio_euro, round(precio * 1.09,2) as precio_dolar from producto;
select nombre as 'nom de producto', precio as euros, round(precio * 1.09,2) as dòlars from producto;
select UPPER(nombre) AS nombre, precio from producto;
select LOWER(nombre) AS nombre, precio from producto;
select nombre, SUBSTRING(UPPER(nombre),1,2) AS 'nombre abreviado' from fabricante;
select nombre, ROUND(precio) from producto;
select nombre, TRUNCATE(precio,0) from producto;
select codigo_fabricante from producto;
select distinct codigo_fabricante from producto;
select nombre from fabricante order by nombre;
select nombre from fabricante order by nombre desc;
select nombre, precio from producto order by nombre asc, precio desc;
select * from fabricante limit 5;
select * from fabricante limit 3,2;
select nombre, precio from producto order by precio limit 1;
select nombre, precio from producto order by precio desc limit 1;
select nombre from producto where codigo_fabricante=2;
select p.nombre, p.precio, f.nombre from producto as p left join fabricante as f on p.codigo_fabricante=f.codigo;
select p.nombre, p.precio, f.nombre from producto as p left join fabricante as f on p.codigo_fabricante=f.codigo order by f.nombre;
select p.codigo, p.nombre, f.codigo, f.nombre from producto as p left join fabricante as f on p.codigo_fabricante=f.codigo;
select p.nombre, p.precio, f.nombre from producto as p left join fabricante as f on p.codigo_fabricante=f.codigo order by p.precio limit 1;
select p.nombre, p.precio, f.nombre from producto as p left join fabricante as f on p.codigo_fabricante=f.codigo order by p.precio desc limit 1;
select * from producto as p left join fabricante as f on p.codigo_fabricante=f.codigo where f.nombre='Lenovo';
select * from producto as p left join fabricante as f on p.codigo_fabricante=f.codigo where f.nombre='Crucial' and p.precio>200;
select * from producto as p left join fabricante as f on p.codigo_fabricante=f.codigo where f.nombre='Asus' or f.nombre='Hewlett-Packard' or f.nombre='Seagate';
select * from producto as p left join fabricante as f on p.codigo_fabricante=f.codigo where f.nombre in ('Asus','Hewlett-Packard','Seagate');
select p.nombre, p.precio from producto as p left join fabricante as f on p.codigo_fabricante=f.codigo where f.nombre LIKE '%e';
select p.nombre, p.precio from producto as p left join fabricante as f on p.codigo_fabricante=f.codigo where f.nombre LIKE '%w%';
select p.nombre, p.precio, f.nombre from producto as p left join fabricante as f on p.codigo_fabricante=f.codigo where p.precio>=180 order by p.precio desc, p.nombre asc;
select distinct f.codigo, f.nombre from fabricante as f inner join producto as p on f.codigo=p.codigo_fabricante;
select f.codigo, f.nombre, p.nombre from fabricante as f left join producto as p on f.codigo=p.codigo_fabricante;
select f.codigo, f.nombre from fabricante as f left join producto as p on f.codigo=p.codigo_fabricante where p.nombre is null;
select * from producto as p left join fabricante as f on p.codigo_fabricante=f.codigo where f.nombre='Lenovo';
select * from producto where precio=(select precio from producto as p left join fabricante as f on p.codigo_fabricante=f.codigo where f.nombre='Lenovo' order by p.precio desc limit 1);
select p.nombre from producto as p left join fabricante as f on p.codigo_fabricante=f.codigo where f.nombre='Lenovo' order by p.precio desc limit 1;
select p.nombre from producto as p left join fabricante as f on p.codigo_fabricante=f.codigo where f.nombre='Hewlett-Packard' order by p.precio limit 1;
select * from producto where precio>=(select precio from producto as p left join fabricante as f on p.codigo_fabricante=f.codigo where f.nombre='Lenovo' order by p.precio desc limit 1);
select * from producto where codigo_fabricante=1 and precio>(select avg(precio) from producto as p left join fabricante as f on p.codigo_fabricante=f.codigo where f.nombre='Asus');